-- CreateTable
CREATE TABLE "sisu_data" (
    "ano" INTEGER,
    "edicao" INTEGER,
    "codigo_etapa" INTEGER,
    "etapa" VARCHAR(50),
    "codigo_ies" INTEGER,
    "nome_ies" VARCHAR(255),
    "sigla_ies" VARCHAR(30),
    "uf_ies" VARCHAR(2),
    "codigo_campus" INTEGER,
    "nome_campus" VARCHAR(255),
    "uf_campus" VARCHAR(2),
    "municipio_campus" VARCHAR(255),
    "codigo_curso" INTEGER,
    "nome_curso" VARCHAR(255),
    "grau" VARCHAR(255),
    "turno" VARCHAR(15),
    "ds_periodicidade" VARCHAR(50),
    "tp_cota" VARCHAR(300),
    "tipo_mod_concorrencia" VARCHAR(300),
    "mod_concorrencia" TEXT,
    "qt_vagas_concorrencia" INTEGER,
    "percentual_bonus" DOUBLE PRECISION,
    "peso_l" DOUBLE PRECISION,
    "peso_ch" DOUBLE PRECISION,
    "peso_cn" DOUBLE PRECISION,
    "peso_m" DOUBLE PRECISION,
    "peso_r" DOUBLE PRECISION,
    "nota_minima_l" DOUBLE PRECISION,
    "nota_minima_ch" DOUBLE PRECISION,
    "nota_minima_cn" DOUBLE PRECISION,
    "nota_minima_m" DOUBLE PRECISION,
    "nota_minima_r" DOUBLE PRECISION,
    "media_minima" DOUBLE PRECISION,
    "cpf" VARCHAR(15),
    "inscricao_enem" VARCHAR(15),
    "inscrito" VARCHAR(255),
    "sexo" VARCHAR(10),
    "data_nascimento" VARCHAR(12),
    "uf_candidato" VARCHAR(2),
    "municipio_candidato" VARCHAR(255),
    "opcao" VARCHAR(20),
    "nota_l" DOUBLE PRECISION,
    "nota_ch" DOUBLE PRECISION,
    "nota_cn" DOUBLE PRECISION,
    "nota_m" DOUBLE PRECISION,
    "nota_r" DOUBLE PRECISION,
    "nota_l_com_peso" DOUBLE PRECISION,
    "nota_ch_com_peso" DOUBLE PRECISION,
    "nota_cn_com_peso" DOUBLE PRECISION,
    "nota_m_com_peso" DOUBLE PRECISION,
    "nota_r_com_peso" DOUBLE PRECISION,
    "nota_candidato" DOUBLE PRECISION,
    "nota_corte" DOUBLE PRECISION,
    "classificacao" VARCHAR(20),
    "aprovado" VARCHAR(520),
    "matricula" VARCHAR(50),
    "id" SERIAL NOT NULL,

    CONSTRAINT "sisu_data_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "sisu_data_id_key" ON "sisu_data"("id");
